### PR TITLE
TGR-74: Adding deprecated note

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Resolves [TGR-74](https://newyorkpubliclibrary.atlassian.net/browse/TGR-74).

As per the LSP Tech Initiative doc and as part of the Remediation Project, this repo and the related AWS Lambda will be deprecated and decommissioned. The lambda has had little to no invocations in the past year (on `nypl-digital-dev` account): https://us-east-1.console.aws.amazon.com/lambda/home?region=us-east-1#/functions/BarcodeService-production?tab=monitoring 

Notes:
- There are other methods used to get a patron's barcode from different repos, and this is hitting Sierra API v3 which is outdated.
```
## Getting Patron Barcodes

Searching within the `nypl` and `nypl-discovery` Github orgs, here is one example of getting a patron's barcodes through a different approach:

- [`nypl-hold-request-consumer`](https://github.com/NYPL/nypl-hold-request-consumer/blob/development/src/helpers/ApiServiceHelper.js#L261) - This app is hitting the `/patrons/{id}` endpoint and getting the patron's barcode from the response's `barCodes` array.
```
- There is a related PR in `DocsService` to remove the endpoint from the Platform API swagger docs https://github.com/NYPL/docsservice/pull/8
- The endpoint will be removed from the AWS API Gateway (for both QA and production).
- There is no QA lambda so only the production instance will be removed.
- This repo will be publicly archived after everything is complete.

[TGR-74]: https://newyorkpubliclibrary.atlassian.net/browse/TGR-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by charmingduchess** [comment]
Can you add to the description of this pr and the readme where those other methods of getting the barcode are?

**Comment by charmingduchess** [comment]
I'm seeing pretty regular invocations over the past 12 months. Where are you seeing zero to very few?
Screenshot 2024-08-22 at 2 26 47 PM

**Comment by EdwinGuzman** [comment]
> Where are you seeing zero to very few?

In the link in the description. The lambda "BarcodeService-production" in the "Monitor" tab and then the invocations graph. Where are you seeing so many?

**Comment by charmingduchess** [comment]
You can also see it [here](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#metricsV2?graph=~(metrics~(~(~'AWS*2fLambda~'Invocations~'FunctionName~'BarcodeService-production~(region~'us-east-1)))~period~900~region~'us-east-1~title~'Invocations~start~'-PT672H~end~'P0D~view~'timeSeries~stacked~false~stat~'Sum)) I had to set the period to a lower resolution (~15 minutes)

If you have the period set to one minute, it just shows the single result. I was reading [about how different resolutions/periods are aggregated ](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch_concepts.html#Metric) and it looks like the low period data isn't kept as long, and then it is aggregated into higher period.

> Data points that are initially published with a shorter period are aggregated together for long-term storage. For example, if you collect data using a period of 1 minute, the data remains available for 15 days with 1-minute resolution. After 15 days this data is still available, but is aggregated and is retrievable only with a resolution of 5 minutes. After 63 days, the data is further aggregated and is available with a resolution of 1 hour. 

When I look at the year [with the higher period](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#metricsV2?graph=~(metrics~(~(~'AWS*2fLambda~'Invocations~'FunctionName~'BarcodeService-production~(region~'us-east-1)))~period~3600~region~'us-east-1~title~'Invocations~start~'-PT8640H~end~'P0D~view~'timeSeries~stacked~false~stat~'Sum)), it shows pretty regularly around 12 calls per day. It's misleading at the lower periods because it looks like there's nothing called. But i think it's just that there's only that one data point left for that period length.

**Review by danamansana — APPROVED** [review]

**Review by charmingduchess — APPROVED** [review]

**Pull request merged**
